name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: download deps
        run: yarn
        
      - name: build ts
        run: yarn tsc

      - name: build css
        run: yarn tailwind -i src/main.css -o site/out.css

      - name: build site
        run: node out/main.js

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: site
